repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2 # https://github.com/pre-commit/mirrors-prettier/tags
    hooks:
      - id: prettier
        files: ^vue/
        additional_dependencies:
          - prettier@2.6.2
          - prettier-plugin-organize-imports@2.3.4
          - prettier-plugin-tailwindcss@0.1.9
          - tailwindcss@2.2.7
